from app.models import db, PlaylistComment, environment, SCHEMA
from sqlalchemy.sql import text
from random import choice

def seed_comments(users, playlists):
    generic_comments = [
        "WOW!!",
        "This shmacks",
        "mid",
        "These tracks make me want to dance like nobody's watching. Pure joy!",
        "Loving the rhythm and melody of this playlist. It's addictive.",
        "Each song on this playlist is like a breath of fresh air. Beautiful and soothing.",
        "This playlist makes my morning commute enjoyable. Thanks for the good vibes.",
        "Can't resist singing along to these songs. They're so catchy!",
        "This playlist showcases the best of different genres. Love the diversity.",
        "These songs transport me to another world. Pure escapism.",
        "This playlist has a great balance of upbeat and mellow tracks. Perfect for any mood.",
        "Loving the selection of artists on this playlist. Such talent!",
        "These songs hit me right in the feels. Emotional and powerful.",
        "This playlist is on repeat mode. Can't tire of these amazing tunes.",
        "These tracks are like therapy for the soul. Instant relaxation.",
        "Loving the vibes of this playlist. Perfect for a lazy Sunday.",
        "Each song on this playlist has its own magic. Captivating and enchanting.",
        "This playlist is my source of inspiration. Gets my creative juices flowing.",
        "Can't help but sing my heart out to these songs. They're infectious!",
        "This playlist is a treasure trove of musical gems. Thank you for sharing your favorites.",
        "Loving the eclectic mix of songs on this playlist. It's like a musical adventure.",
        "These tunes bring back memories of carefree days. Nostalgic and wonderful.",
        "This playlist is a work of art. It deserves all the appreciation.",
        "Can't resist swaying to the rhythm of these songs. Pure bliss!",
        "This playlist has the perfect blend of upbeat and chill tracks. Great for any occasion.",
        "These songs have the power to uplift my mood instantly. Thank you for the positive vibes.",
        "Loving the diversity in this playlist. From rock to pop to jazz, it has it all.",
        "This playlist has introduced me to new artists and genres. Broadening my musical horizons.",
        "Can't help but smile while listening to these songs. They bring so much joy.",
        "This playlist is like a time machine. Takes me back to the good old days.",
        "These tracks make me want to hit the dance floor. They're so infectious!",
        "Loving the combination of old classics and modern hits on this playlist.",
        "This playlist has a perfect balance of fast-paced and slow songs. Keeps things interesting.",
        "Can't resist singing along to every track. These songs have become my favorites.",
        "This playlist has a magical charm. It transports me to another world.",
        "These tunes are perfect for a relaxing evening at home. Helps me unwind.",
        "Loving the energy and passion in these songs. They're full of life.",
        "This playlist has a song for every mood and occasion. It's my musical companion.",
        "These tracks make me want to turn up the volume and let loose. So much fun!",
        "This playlist is a true masterpiece. Each song flows seamlessly into the next.",
        "Can't help but get lost in the melodies of these songs. They're captivating.",
        "Loving the lyrics of these tracks. They resonate with me on a deep level.",
        "This playlist is my sanctuary. It provides solace in both good and bad times.",
        "These songs are like a burst of sunshine. They brighten up my day.",
        "This playlist has the perfect mix of old favorites and new discoveries. Keeps things fresh.",
        "Can't resist tapping my feet and nodding my head to these beats. They're infectious!",
        "Loving the diversity in this playlist. It celebrates music from all around the world.",
        "These tracks make me want to grab a guitar and start jamming. They're so inspiring.",
        "This playlist has the power to bring people together. Music knows no boundaries.",
        "Can't help but get lost in the melodies and harmonies of these songs. They're mesmerizing.",
        "This playlist is my escape from reality. It allows me to get lost in the music.",
        "These tunes are perfect for a romantic evening. Sets the mood just right.",
        "This playlist is a hidden gem. So glad I discovered it.",
        "Each song on this playlist has a unique vibe. Keeps things interesting.",
        "Loving the smooth transitions between tracks. It's a seamless listening experience.",
        "These songs bring back memories of unforgettable moments in my life.",
        "Can't help but groove to the rhythm of these tracks. They're so infectious!",
        "This playlist is my go-to when I need a boost of motivation. It gets me pumped up.",
        "Loving the combination of old classics and modern hits. It's the best of both worlds.",
        "These tunes have a way of touching my soul. They speak to me on a deeper level.",
        "This playlist is a testament to the power of music. It has the ability to evoke emotions.",
        "Can't resist turning up the volume and singing along to these anthems. They're empowering.",
        "This playlist takes me on a journey through different emotions. It's a rollercoaster of feelings.",
        "Loving the diversity in this playlist. From rock to hip-hop to electronic, it covers it all.",
        "These songs have become the soundtrack of my life. They accompany me through ups and downs.",
        "This playlist is a perfect companion for a road trip. It sets the right mood for the adventure.",
        "Can't help but get lost in the melodies and lyrics of these songs. They're captivating.",
        "Loving the energy and enthusiasm in these tracks. They ignite a fire within me.",
        "This playlist has the power to transport me to different places and times. It's magical.",
        "These tunes have a way of putting a smile on my face. They're pure happiness.",
        "This playlist is a true masterpiece. It's evident that a lot of thought went into curating it.",
        "Can't resist recommending this playlist to all my friends. It's a musical gem.",
        "Loving the nostalgia these songs bring. They remind me of cherished moments from the past.",
        "These tracks have a way of making me feel understood. They're like a friend who gets me.",
        "This playlist is my source of comfort during tough times. It provides solace and strength.",
        "Can't help but appreciate the artistry and talent behind these songs. They're exceptional.",
        "Loving the storytelling aspect of these tracks. They paint vivid pictures in my mind.",
        "This playlist has a great balance of introspective and uplifting songs. It's a perfect mix.",
        "These tunes have a way of soothing my soul. They're a balm for the weary heart.",
        "This playlist is a time capsule of emotions. It captures the essence of different feelings.",
        "Can't resist sharing this playlist with everyone I know. It's too good to keep to myself.",
        "Loving the diversity in genres represented on this playlist. It broadens my musical taste.",
        "These songs have a way of resonating with me on a personal level. They speak my truth.",
        "This playlist is a treasure trove of musical discoveries. It's a journey of exploration.",
        "These tracks make me appreciate the beauty of music. It's a universal language that connects us.",
        "Can't help but be in awe of the talent showcased in these songs. It's inspiring.",
        "Loving the smooth and mellow vibes of this playlist. It's perfect for unwinding after a long day.",
        "These tunes have a way of capturing the essence of different moods. They're relatable.",
        "This playlist has the power to heal. It brings comfort and solace during difficult times.",
        "Can't resist getting lost in the melodies and rhythms of these tracks. They transport me.",
        "Loving the way this playlist sets the atmosphere. It creates the perfect ambiance.",
        "These songs have a way of evoking nostalgia and memories. They're filled with emotions.",
        "This playlist is a testament to the power of music in bringing people together.",
        "Can't help but appreciate the intricate instrumentation and production in these tracks.",
        "Loving the diversity in vocal styles and performances. It's a showcase of talent.",
        "These tunes have a way of sparking creativity and inspiration. They fuel my imagination.",
        "This playlist is a true masterpiece. It's a work of art that deserves recognition.",
        "Can't resist the urge to dance and move to the beats of these tracks. They're infectious.",
        "Loving the fusion of different genres and influences in this playlist. It's a musical fusion.",
        "These songs have a way of capturing the essence of different seasons and moods.",
        "This playlist is a constant companion during my workouts. It keeps me motivated and energized.",
        "Can't help but appreciate the lyrical depth and storytelling in these tracks. They're poetic.",
        "Loving the surprises and unexpected gems in this playlist. It's full of pleasant discoveries.",
        "These tunes have a way of bringing people together. They create a sense of unity and connection.",
        "This playlist is a reminder of the power of music to uplift and inspire. It's uplifting.",
        "Can't resist the charm and charisma of these songs. They're irresistibly catchy.",
        "Loving the versatility and range of emotions in this playlist. It's a journey through feelings.",
        "These songs have a way of capturing the essence of different cultures and traditions.",
        "This playlist is my escape from reality. It allows me to get lost in the music.",
        "These tunes are perfect for a romantic evening. Sets the mood just right.",
        "This playlist is a hidden gem. So glad I discovered it.",
    ]

    all_comments = [PlaylistComment(
        user = choice(users),
        playlist = choice(playlists),
        content = comment
    ) for comment in generic_comments]

    add = [db.session.add(comment) for comment in all_comments]

    db.session.commit()


def undo_comments():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.comments RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM comments"))

    db.session.commit()
